version: '3.7'

services:
  
  payara:
    build: ../../images/payara
    environment:
      PAYARA_ARGS: "--debug"
    ports:
      - 8080:8080
      - 4848:4848
      - 9009:9009

  wildfly:
    build: ../../images/wildfly
    ports:
      - 9090:9090
      - 9990:9990
      - 8787:8787
  
  db:
    build: ../../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: amt_notes
      MYSQL_ROOT_PASSWORD: adminadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
    restart: always
    depends_on:
     - db
    ports:
     - 8888:80

