version: '3'
services:
  payara:
    build: ../images/payara
    environment:
     - ADMIN_PASSWORD=adminadmin
    links:
     - mysql:db
    ports:
     - "8080:8080"
     - "4848:4848"
  
  mysql:
    build: ../images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminadmin

  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminadmin
    ports:
     - "6060:80"
    links:
     - mysql:db
  